steps:
  - name: 'hashicorp/terraform:1.3.4'
    args: ['init']
    dir: 'terraform/environments/prod'
  - name: 'hashicorp/terraform:1.3.4'
    args: ['plan']
    dir: 'terraform/environments/prod'
  - name: 'hashicorp/terraform:1.3.4'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ $BRANCH_NAME == "main" ]; then
          terraform apply -auto-approve
        else
          echo "SKIPPING APPLYING"
        fi
    dir: 'terraform/environments/prod'
    secretEnv: ['TF_VAR_cloud_storage_service_account']
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/snowflake-podb-bqfun-cloud-storage-service-account/versions/latest
      env: 'TF_VAR_cloud_storage_service_account'
