steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/source/houjinbangou-latest:latest
      - .
    dir: dockerfiles/houjinbangou_latest
images:
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/source/houjinbangou-latest:latest
