on: [pull_request]
jobs:
  terraform_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -recursive
        working-directory: ./terraform
      - id: diff
        run: git diff --quiet --exit-code
        continue-on-error: true
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -am 'terraform fmt'
          git push
          exit 1
        if: steps.diff.outcome == 'failure'
