on: [pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/environments/prod
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/120299025068/locations/global/workloadIdentityPools/github-actions/providers/main'
          service_account: 'github-actions-terraform-plan@jpdata.iam.gserviceaccount.com'
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: TF_LOG=DEBUG terraform plan
        env:
          TF_VAR_cloud_storage_service_account: ${{ secrets.TF_VAR_CLOUD_STORAGE_SERVICE_ACCOUNT }}

