on: [pull_request]
jobs:
  terraform_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -recursive
        working-directory: ./terraform
      - id: git_diff
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git diff --quiet || git commit -am "terraform fmt" || echo "No changes to commit."
      - if: steps.git_diff.outputs.changed == 'true'
        run: git push
