on: [push]
jobs:
  terraform_job:
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -check -recursive
        working-directory: ./terraform
